-- SCRIPT PARA DELETAR TODAS AS TABELAS E SEQUENCES DA PLATAFORMA MEDIX

-- DELETANDO AS TABELAS
DROP TABLE TB_MEDI_AGENDAMENTO;
DROP TABLE TB_MEDI_COLABORADOR_ESPECIALIDADE;
DROP TABLE TB_MEDI_RECURSO;
DROP TABLE TB_MEDI_COLABORADOR;
DROP TABLE TB_MEDI_PACIENTE;
DROP TABLE TB_MEDI_ESPECIALIDADE;
DROP TABLE TB_MEDI_USUARIO;
DROP TABLE TB_MEDI_UNIDADE_SAUDE;